-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 00:43:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bot` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bot` (
  `bot_id` BIGINT(20) UNSIGNED NOT NULL,
  `status` ENUM('idle', 'en_route', 'charging', 'error') NOT NULL DEFAULT 'idle',
  `battery_level` TINYINT(3) UNSIGNED NULL DEFAULT 100,
  `last_checkin` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`bot_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idbot_UNIQUE` ON `mydb`.`Bot` (`bot_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `location_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `latitude` DECIMAL(9,6) NULL,
  `longitude` DECIMAL(9,6) NULL,
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idLocation_UNIQUE` ON `mydb`.`Location` (`location_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`Location` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`path_edge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`path_edge` ;

CREATE TABLE IF NOT EXISTS `mydb`.`path_edge` (
  `edge_id` BIGINT(20) UNSIGNED NOT NULL,
  `from_id` BIGINT(20) UNSIGNED NOT NULL,
  `to_id` BIGINT(20) UNSIGNED NOT NULL,
  `distance` FLOAT NOT NULL,
  `is_blocked` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`edge_id`),
  CONSTRAINT `fk_path_edge_Location1`
    FOREIGN KEY (`from_id`)
    REFERENCES `mydb`.`Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_path_edge_Location2`
    FOREIGN KEY (`to_id`)
    REFERENCES `mydb`.`Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idpath_edge_UNIQUE` ON `mydb`.`path_edge` (`edge_id` ASC) VISIBLE;

CREATE INDEX `fk_path_edge_Location1_idx` ON `mydb`.`path_edge` (`from_id` ASC) VISIBLE;

CREATE INDEX `fk_path_edge_Location2_idx` ON `mydb`.`path_edge` (`to_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `role_id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` ENUM('admin', 'user') NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `role_id_UNIQUE` ON `mydb`.`role` (`role_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `mydb`.`role` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` BIGINT(20) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` CHAR(60) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `role_id` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_role2`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `mydb`.`user` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `mydb`.`user` (`user_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`user` (`email` ASC) VISIBLE;

CREATE INDEX `fk_user_role2_idx` ON `mydb`.`user` (`role_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`delivery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `delivery_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bot_id` BIGINT(20) UNSIGNED NOT NULL,
  `start_location` BIGINT(20) UNSIGNED NULL,
  `end_location` BIGINT(20) UNSIGNED NULL,
  `pin_hash` CHAR(60) NULL,
  `status` ENUM('pending', 'in_progress', 'delivered', 'failed', 'cancelled') NULL DEFAULT 'pending',
  `started_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `created_at` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`delivery_id`, `user_id`),
  CONSTRAINT `fk_delivery_Bot1`
    FOREIGN KEY (`bot_id`)
    REFERENCES `mydb`.`Bot` (`bot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_delivery_Bot1_idx` ON `mydb`.`delivery` (`bot_id` ASC) VISIBLE;

CREATE INDEX `fk_delivery_user2_idx` ON `mydb`.`delivery` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sensor` (
  `sensor_id` BIGINT(20) UNSIGNED NOT NULL,
  `bot_id` BIGINT(20) NOT NULL,
  `sensor_type` ENUM('sound_left', 'sound_right', 'encoder_left', 'encoder_right') NOT NULL,
  `value` FLOAT NULL,
  `recorded_at` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sensor_id`),
  CONSTRAINT `fk_Sensor_Bot`
    FOREIGN KEY (`bot_id`)
    REFERENCES `mydb`.`Bot` (`bot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idSensor_UNIQUE` ON `mydb`.`Sensor` (`sensor_id` ASC) VISIBLE;

CREATE INDEX `fk_Sensor_Bot_idx` ON `mydb`.`Sensor` (`bot_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`servo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servo` (
  `report_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bot_id` BIGINT(20) UNSIGNED NOT NULL,
  `servo_id` TINYINT(1) UNSIGNED NULL,
  `action` ENUM('hold', 'release', 'lock', 'unlock') NOT NULL,
  `executed_at` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_servo_Bot1`
    FOREIGN KEY (`bot_id`)
    REFERENCES `mydb`.`Bot` (`bot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_servo_Bot1_idx` ON `mydb`.`servo` (`bot_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `report_id_UNIQUE` ON `mydb`.`servo` (`report_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `Log_id` BIGINT(20) UNSIGNED NOT NULL,
  `bot_id` BIGINT(20) UNSIGNED NOT NULL,
  `event_type` ENUM('obstacle_detected', 'reroute', 'delivery_started', 'delivery_completed', 'error') NOT NULL,
  `message` MEDIUMTEXT NULL,
  `created_at` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Log_id`),
  CONSTRAINT `fk_Logs_Bot1`
    FOREIGN KEY (`bot_id`)
    REFERENCES `mydb`.`Bot` (`bot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Logs_Bot1_idx` ON `mydb`.`Log` (`bot_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`path_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`path_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`path_history` (
  `history_id` BIGINT(20) UNSIGNED NOT NULL,
  `delivery_id` BIGINT(20) UNSIGNED NULL,
  `sequence_order` INT UNSIGNED NULL,
  `location_id` BIGINT(20) UNSIGNED NULL,
  `timestamp` TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`history_id`),
  CONSTRAINT `fk_path_history_delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `mydb`.`delivery` (`delivery_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_path_history_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_path_history_delivery1_idx` ON `mydb`.`path_history` (`delivery_id` ASC) VISIBLE;

CREATE INDEX `fk_path_history_Location1_idx` ON `mydb`.`path_history` (`location_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
